name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg ripgrep atomicparsley

    - name: Install freyr
      run: npm ci && npm link

    - name: Prep Testing Stage
      run: |
        mkdir -p ./CI/{spotify,apple_music,deezer}/{track,album,artist,playlist}

        cat << EOF > ./CI/prep.sh
          RG_SRC="\$(which rg)"
          rg() {
            printf "rg: pattern: /\$@/" > /dev/stderr
            \$RG_SRC --fixed-strings --passthru "\$@"
            if [[ \$? == 0 ]]; then
              echo " (matched)" > /dev/stderr
            else
              echo " (failed to match)" > /dev/stderr
              return 1
            fi
          }

          freyr() {
            echo "::group::[\$attempts/3] Downloading..."
            script -qfc "freyr \$@" /dev/null | tee .freyr_log
            echo "::endgroup::"
            i=\$(cat .freyr_log | \$RG_SRC -n '.' | \$RG_SRC --fixed-strings '[•] Embedding Metadata' | cut -d':' -f1)
            if [[ \$i ]]; then
              echo "::group::[\$attempts/3] View Download Status"
              cat .freyr_log | tail +\$i
              echo "::endgroup::"
            fi
          }

          exec_retry() {
            cmd="\$(cat)" && attempts=1
            until eval "\$cmd"; do
              echo "::endgroup::"
              if (( attempts < 3 )); then
                echo "::warning::[\$attempts/3] Download failed, retrying.."
                : \$(( attempts += 1 ))
              else
                echo "::error::[\$attempts/3] Download failed."
                return 1
              fi
            done
            echo "::endgroup::"
            echo "::group::View Files"
            STAGE=\$(realpath --relative-to=../.. .) && cd ../..
            tree -sh \$STAGE
            echo "::endgroup::"
          }

          validate() {
            echo "::group::[\$attempts/3] Verifying..."
            res=\$(cat .freyr_log | rg "[•] Collation Complete")
            for arg in "\$@"; do
              res=\$(echo "\$res" | rg "\$arg")
            done > /dev/null
          }
        EOF

    - name: Spotify - Download Track
      run: |
        . ./CI/prep.sh && cd ./CI/spotify/track

        exec_retry << EOF
          freyr https://open.spotify.com/track/5FNS5Vj69AhRGJWjhrAd01
          validate \
            "[•] Total tracks: [01]" \
            "✕ Failed:  [00]"
        EOF

    - name: Spotify - Download Album
      run: |
        . ./CI/prep.sh && cd ./CI/spotify/album

        exec_retry << EOF
          freyr https://open.spotify.com/album/2D23kwwoy2JpZVuJwzE42B
          validate \
            "[•] Total tracks: [04]" \
            "✕ Failed:  [00]"
        EOF

    - name: Spotify - Download Artist
      run: |
        . ./CI/prep.sh && cd ./CI/spotify/artist

        exec_retry << EOF
          freyr https://open.spotify.com/artist/4adSXA1GDOxNG7Zw89YHyz
          validate "✕ Failed:  [00]"
        EOF

    # - name: Spotify - Download Playlist

    - name: Apple Music - Download Track
      run: |
        . ./CI/prep.sh && cd ./CI/apple_music/track

        exec_retry << EOF
          freyr https://music.apple.com/us/album/elio-irl/1547735824?i=1547736100
          validate \
            "[•] Total tracks: [01]" \
            "✕ Failed:  [00]"
        EOF

    - name: Apple Music - Download Album
      run: |
        . ./CI/prep.sh && cd ./CI/apple_music/album

        exec_retry << EOF
          freyr https://music.apple.com/us/album/im-sorry-im-not-sorry-ep/1491795443
          validate \
            "[•] Total tracks: [04]" \
            "✕ Failed:  [00]"
        EOF

    - name: Apple Music - Download Artist
      run: |
        . ./CI/prep.sh && cd ./CI/apple_music/artist

        exec_retry << EOF
          freyr https://music.apple.com/us/artist/mazie/1508029053
          validate "✕ Failed:  [00]"
        EOF

    # - name: Apple Music - Download Playlist

    - name: Deezer - Download Track
      run: |
        . ./CI/prep.sh && cd ./CI/deezer/track

        exec_retry << EOF
          freyr https://www.deezer.com/en/track/1189202982
          validate \
            "[•] Total tracks: [01]" \
            "✕ Failed:  [00]"
        EOF

    - name: Deezer - Download Album
      run: |
        . ./CI/prep.sh && cd ./CI/deezer/album

        exec_retry << EOF
          freyr https://www.deezer.com/en/album/123330212
          validate \
            "[•] Total tracks: [04]" \
            "✕ Failed:  [00]"
        EOF

    - name: Deezer - Download Artist
      run: |
        . ./CI/prep.sh && cd ./CI/deezer/artist

        exec_retry << EOF
          freyr https://www.deezer.com/en/artist/14808825
          validate "✕ Failed:  [00]"
        EOF

    # - name: Deezer - Download Playlist

  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build
      run: docker build -t freyrcli/freyrjs .
